/**
 * Generates random names in the style of Drizzle migrations
 * Format: {adjective}_{noun}
 */

const adjectives = [
  "great",
  "green",
  "overjoyed",
  "milky",
  "salty",
  "slim",
  "demonic",
  "shiny",
  "eager",
  "brief",
  "simple",
  "chief",
  "friendly",
  "goofy",
  "cloudy",
  "workable",
  "parallel",
  "massive",
  "steady",
  "wide",
  "cold",
  "premium",
  "amazing",
  "jazzy",
  "classy",
  "gorgeous",
  "melted",
  "violet",
  "sloppy",
  "handy",
  "good",
  "flashy",
  "wealthy",
  "wakeful",
  "lively",
  "open",
  "small",
  "known",
  "fluffy",
  "black",
  "confused",
  "melodic",
  "rich",
  "lucky",
  "slippery",
  "low",
  "gigantic",
  "daffy",
  "mysterious",
  "groovy",
  "gray",
  "thick",
  "solid",
  "bright",
  "grey",
  "soft",
  "clammy",
  "daily",
  "light",
  "yellow",
  "hot",
  "high",
  "clean",
  "amusing",
  "greedy",
  "late",
  "parched",
  "chubby",
  "real",
  "purple",
  "luxuriant",
  "yummy",
  "absent",
  "reflective",
  "outstanding",
  "first",
  "adorable",
  "lush",
  "wooden",
  "burly",
  "sweet",
  "regular",
  "volatile",
  "new",
  "last",
  "thankful",
  "ambitious",
  "perfect",
  "blue",
  "fixed",
  "exotic",
  "stiff",
  "lumpy",
  "little",
  "free",
  "windy",
  "hesitant",
  "puzzling",
  "loving",
  "gifted",
  "colorful",
  "rare",
  "misty",
  "pale",
  "large",
  "sturdy",
];

const nouns = [
  "baron",
  "rogue",
  "gambit",
  "storm",
  "cyclops",
  "wolverine",
  "phoenix",
  "colossus",
  "nightcrawler",
  "jubilee",
  "bishop",
  "cable",
  "domino",
  "deadpool",
  "psylocke",
  "magik",
  "warlock",
  "cannonball",
  "sunspot",
  "mirage",
  "wolfsbane",
  "cypher",
  "magma",
  "karma",
  "warpath",
  "banshee",
  "siryn",
  "forge",
  "longshot",
  "dazzler",
  "havok",
  "polaris",
  "quicksilver",
  "scarlet_witch",
  "vision",
  "wonder_man",
  "beast",
  "angel",
  "iceman",
  "kitty_pryde",
  "shadowcat",
  "lockheed",
  "rachel_grey",
  "hope_summers",
  "x23",
  "daken",
  "fantomex",
  "mystique",
  "sabretooth",
  "juggernaut",
  "magneto",
  "apocalypse",
  "sinister",
  "sentinels",
  "nimrod",
  "bastion",
  "proteus",
  "legion",
  "onslaught",
  "stryfe",
  "exodus",
  "acolytes",
  "marauders",
  "hellfire_club",
  "purifiers",
  "reavers",
  "morlocks",
  "genosha",
  "krakoa",
  "asteroid_m",
  "danger_room",
  "cerebro",
  "blackbird",
  "fastball_special",
  "sentinel_program",
  "weapon_x",
  "department_h",
  "alpha_flight",
  "excalibur",
  "x_force",
  "x_factor",
  "new_mutants",
  "generation_x",
  "academy_x",
  "hellions",
  "corsairs",
  "shi_ar",
  "brood",
  "phalanx",
  "techno_organic",
  "legacy_virus",
];

function capitalize(str: string): string {
  return str
    .split("_")
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join("");
}

export function generatePlayerName(): string {
  // Use timestamp + crypto random for maximum uniqueness
  const timestamp = Date.now();
  const cryptoRandom1 = crypto.getRandomValues(new Uint32Array(1))[0];
  const cryptoRandom2 = crypto.getRandomValues(new Uint32Array(1))[0];

  const seed1 = (timestamp + cryptoRandom1) % adjectives.length;
  const seed2 = (timestamp * 2 + cryptoRandom2) % nouns.length;

  const adjective = adjectives[seed1];
  const noun = nouns[seed2];
  return `${capitalize(adjective)}${capitalize(noun)}`;
}
