// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rowId: __t.u64().primaryKey().name("row_id"),
  gameId: __t.string().name("game_id"),
  identity: __t.identity(),
  name: __t.string(),
  playerId: __t.string().name("player_id"),
  isBot: __t.bool().name("is_bot"),
  isSpectator: __t.bool().name("is_spectator"),
  connected: __t.bool(),
});
