// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  gameId: __t.string(),
  senderName: __t.string(),
  content: __t.string(),
  timestamp: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Game = __t.object("Game", {
  id: __t.string(),
  status: __t.string(),
  isSinglePlayer: __t.bool(),
  hostIdentity: __t.identity(),
});
export type Game = __Infer<typeof Game>;

export const GameCommand = __t.object("GameCommand", {
  id: __t.u64(),
  gameId: __t.string(),
  playerId: __t.string(),
  commandJson: __t.string(),
  processed: __t.bool(),
});
export type GameCommand = __Infer<typeof GameCommand>;

export const GamePlayer = __t.object("GamePlayer", {
  rowId: __t.u64(),
  gameId: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  playerId: __t.string(),
  isBot: __t.bool(),
  isSpectator: __t.bool(),
  connected: __t.bool(),
});
export type GamePlayer = __Infer<typeof GamePlayer>;

export const GameRequest = __t.object("GameRequest", {
  id: __t.u64(),
  fromIdentity: __t.identity(),
  toIdentity: __t.identity(),
});
export type GameRequest = __Infer<typeof GameRequest>;

export const GameSnapshot = __t.object("GameSnapshot", {
  gameId: __t.string(),
  stateJson: __t.string(),
  eventsJson: __t.string(),
  version: __t.u64(),
});
export type GameSnapshot = __Infer<typeof GameSnapshot>;

export const LobbyPlayer = __t.object("LobbyPlayer", {
  identity: __t.identity(),
  name: __t.string(),
  clientId: __t.string(),
  connected: __t.bool(),
});
export type LobbyPlayer = __Infer<typeof LobbyPlayer>;

