// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptRequestReducer from "../accept_request_reducer";
import CancelRequestReducer from "../cancel_request_reducer";
import CreateSingleplayerGameReducer from "../create_singleplayer_game_reducer";
import JoinGameAsSpectatorReducer from "../join_game_as_spectator_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import LeaveGameReducer from "../leave_game_reducer";
import LeaveLobbyReducer from "../leave_lobby_reducer";
import MarkCommandProcessedReducer from "../mark_command_processed_reducer";
import PushStateReducer from "../push_state_reducer";
import RequestGameReducer from "../request_game_reducer";
import ResignGameReducer from "../resign_game_reducer";
import SendChatReducer from "../send_chat_reducer";
import SubmitCommandReducer from "../submit_command_reducer";

export type AcceptRequestParams = __Infer<typeof AcceptRequestReducer>;
export type CancelRequestParams = __Infer<typeof CancelRequestReducer>;
export type CreateSingleplayerGameParams = __Infer<typeof CreateSingleplayerGameReducer>;
export type JoinGameAsSpectatorParams = __Infer<typeof JoinGameAsSpectatorReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type LeaveGameParams = __Infer<typeof LeaveGameReducer>;
export type LeaveLobbyParams = __Infer<typeof LeaveLobbyReducer>;
export type MarkCommandProcessedParams = __Infer<typeof MarkCommandProcessedReducer>;
export type PushStateParams = __Infer<typeof PushStateReducer>;
export type RequestGameParams = __Infer<typeof RequestGameReducer>;
export type ResignGameParams = __Infer<typeof ResignGameReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SubmitCommandParams = __Infer<typeof SubmitCommandReducer>;

