/**
 * Regenerate src/config/models.generated.ts from the AI Gateway catalog.
 *
 *   bun run models:refresh
 *
 * Keeps every model the account can actually call: the gateway refuses any
 * model with zdr "none" outright, and routes "some" to its ZDR provider.
 * Everything the gateway cannot know lives in src/config/model-overrides.ts.
 */
import {
  DEFAULT_PROVIDER_COLOR,
  DENIED_MODELS,
  DENIED_PROVIDERS,
  ID_ALIASES,
  MODEL_QUIRKS,
  PROVIDER_ALIASES,
  PROVIDER_COLORS_BY_NAME,
} from "../src/config/model-overrides";

const GATEWAY_MODELS_URL = "https://ai-gateway.vercel.sh/v1/models";
const OUTPUT_PATH = "src/config/models.generated.ts";
const PER_MILLION = 1_000_000;

type GatewayModel = {
  id: string;
  name: string;
  owned_by: string;
  type: string;
  zdr: "all" | "some" | "none";
  modalities?: { output?: string[] };
  pricing?: { input?: string; output?: string };
};

const pricePerMillion = (raw: string | undefined): number =>
  Math.round(Number(raw ?? 0) * PER_MILLION * 1e6) / 1e6;

const shortId = (model: GatewayModel): string =>
  ID_ALIASES[model.id] ?? model.id.split("/").slice(1).join("/");

const providerOf = (model: GatewayModel): string =>
  PROVIDER_ALIASES[model.owned_by] ?? model.owned_by;

/** Game moves come back as text. A model that only emits images cannot answer. */
const emitsText = (model: GatewayModel): boolean => {
  const out = model.modalities?.output;
  return out === undefined || out.includes("text");
};

const isPlayable = (model: GatewayModel): boolean =>
  (model.type === "language" || model.type === "evaluation") &&
  model.zdr !== "none" &&
  emitsText(model) &&
  DENIED_MODELS[model.id] === undefined &&
  DENIED_PROVIDERS[providerOf(model)] === undefined;

const quote = (value: string): string => JSON.stringify(value);

const entryFor = (model: GatewayModel): string => {
  const id = shortId(model);
  const provider = providerOf(model);
  const quirks = MODEL_QUIRKS[id];
  const lines = [
    `    id: ${quote(id)},`,
    `    fullName: ${quote(model.id)},`,
    `    displayName: ${quote(model.name)},`,
    `    provider: ${quote(provider)},`,
    `    color: ${quote(PROVIDER_COLORS_BY_NAME[provider] ?? DEFAULT_PROVIDER_COLOR)},`,
    `    inputPrice: ${pricePerMillion(model.pricing?.input)},`,
    `    outputPrice: ${pricePerMillion(model.pricing?.output)},`,
    ...(model.type === "evaluation" ? [`    evaluation: true,`] : []),
    ...(quirks?.structuredOutput
      ? [`    structuredOutput: ${quote(quirks.structuredOutput)},`]
      : []),
    ...(quirks?.gatewayProviders
      ? [`    gatewayProviders: ${JSON.stringify(quirks.gatewayProviders)},`]
      : []),
    ...(quirks?.maxInstances
      ? [`    maxInstances: ${quirks.maxInstances},`]
      : []),
  ];
  return `  {\n${lines.join("\n")}\n  },`;
};

const apiKey = process.env.AI_GATEWAY_API_KEY;
if (!apiKey) throw new Error("AI_GATEWAY_API_KEY is not set");

const response = await fetch(GATEWAY_MODELS_URL, {
  headers: { Authorization: `Bearer ${apiKey}` },
});
if (!response.ok) {
  throw new Error(`Gateway returned ${response.status} ${response.statusText}`);
}
const { data } = (await response.json()) as { data: GatewayModel[] };

const playable = data
  .filter(isPlayable)
  .sort((a, b) =>
    providerOf(a) === providerOf(b)
      ? shortId(a).localeCompare(shortId(b))
      : providerOf(a).localeCompare(providerOf(b)),
  );

const collisions = Object.entries(
  playable.reduce<Record<string, string[]>>(
    (acc, model) => ({
      ...acc,
      [shortId(model)]: [...(acc[shortId(model)] ?? []), model.id],
    }),
    {},
  ),
).filter(([, ids]) => ids.length > 1);
if (collisions.length > 0) {
  throw new Error(
    `Short id collision, add an ID_ALIASES entry: ${JSON.stringify(collisions)}`,
  );
}

const staleQuirks = Object.keys(MODEL_QUIRKS).filter(
  id => !playable.some(model => shortId(model) === id),
);

const generated = `// GENERATED by scripts/refresh-models.ts on ${new Date().toISOString().slice(0, 10)}. Do not edit.
// Source: ${GATEWAY_MODELS_URL}, every language or evaluation model the account
// can call (the gateway refuses zdr "none" and routes "some" to a ZDR provider).
// Quirks, colours, id aliases and denials live in ./model-overrides.ts.
import type { ModelConfig } from "./model-config";

export const GENERATED_MODELS = [
${playable.map(entryFor).join("\n")}
] as const satisfies readonly ModelConfig[];
`;

await Bun.write(OUTPUT_PATH, generated);

const providers = new Set(playable.map(providerOf));
console.log(`wrote ${playable.length} models across ${providers.size} providers to ${OUTPUT_PATH}`);
console.log(`skipped ${data.length - playable.length} of ${data.length} catalog entries`);
if (staleQuirks.length > 0) {
  console.log(`stale MODEL_QUIRKS entries (no longer in the catalog): ${staleQuirks.join(", ")}`);
}
